### ISSUE TITLE
Modify additional_metadata to better support frontend

### ISSUE THREAD

**Issue by Philinphiladelphia** [AlexsLemonade/resources-portal#134]
### Context

Frontend development will be easier if most attributes are not nested. We should have as many attributes as possible on the outer level.

### Problem or idea

Move all common attributes on materials to the outer level.

### Solution or next step

![Screen Shot 2020-04-20 at 5.09.45 PM.png](https://images.zenhubusercontent.com/5e8347a972c6f5ba09ada022/c6d98129-fb79-4d67-adf9-64c7866f521c)

Move these attributes into the model directly. This will require updates to the test data and Elasticsearch parameters.

**Comment by davidsmejia** [comment]
* material model
  * [ ] add organism(s) attribute +  we might need to support multiple will verify
  * [ ] we are going to want to move pulcation and preprint attributes to the material (inluding embargo_date)
  * [ ] add nullable import_source with the following options: (if possible add material.category and material.import_source agreement)
    * GEO_SRA(dataset)
    * DBGAP (dataset)
    * ATCC (cell line)
    * ADD_GENE (plasmid)
    * PROTOCOLS_IO (protocols)
    * JACKSON_LAB (Model organisms - mouse specific repo)
    * ZIRC_ZFIN (Model organisms - zebrafish specific repo)
    * OTHER

* test data
  * [ ] add an import_source to all items
  * [ ] can we change from python "True" "False" to valid json, i'm pretty sure it would parse
* cell line
  * [ ] change tissue to tissue histology make it a string so like "brain/brain tumor"
  * [ ] available quality fields is on the search result but not in the form?
  * [ ] for the imported cell line can we add additional_metadata.import_source to be `ATCC`
  * [ ] change of "Cryopreservation" to lowercase
  * [ ] change "str" to `str_profile`
* dataset
  * [ ] verify that accession can also be the ncbi study id ie `phs000328.v2.p1` or maybe change the name?
  * [ ] or change accession to accession_id

* model organism - no additional changes
* plasmids - no additional changes
* Protocols - i think this looks good :shrug:

* PDX_MODEL
  * [ ] maybe change the tumor grade to something like "AJCC IV"
  * [ ] current_treatment_protocol, current_treatment_drug, and prior_treamtment_protocol
  * [ ] response_to_prior_treatment (add prior)
  * [ ] submitter_patient_id instead of patient_id
  * [ ] `primary_tissue_of_origin` (add primary)
*Other looks good

**Comment by davidsmejia** [comment]
going to @kurtwheeler @dvenprasad for comments

**Comment by kurtwheeler** [comment]
> add organism(s) attribute + we might need to support multiple will verify

How do we want to do organisms, just a list of strings? Do we need an organism model? It doesn't seem as necessary as it was for refinebio, but organisms can get tricky, especially once you get into organisms with strains or if we ever wanted to be able to search on genus, ect.

 If we do strings, what format are we using?

> add an import_source to all items

I think some of the test data intentionally doesn't have this to simulate it being listed.

> change tissue to tissue histology

Do you mean the sub_field name? Should it be `tissue_histology` then?

> change accession to accession_id

Definitely agree with this one. I've never loved the use of `accession` but `id` makes it a bit clearer.

That's about all I've got. Also looking forward to hearing Deepa's thoughts.

**Comment by davidsmejia** [comment]
> How do we want to do organisms, just a list of strings?

Yeah I think that would be easiest for now

> I think some of the test data intentionally doesn't have this to simulate it being listed.

Yeah sorry to clarify: all resources should have an imported_source (column on the table) null if listed and then populated with the appropriate source for the material category ( we need to present this to the user )

> Do you mean the sub_field name? Should it be tissue_histology then?

yeah material.additional_metadata.tissue_histology for pdx + cell line - so just need to update cell line to reflect this

**Comment by dvenprasad** [comment]
**Cell Lines**
All of these sound good.  Have one comment

>available quality fields is on the search result but not in the form?

It is only on the [list-cell-line form](https://invis.io/NAVYSEBXJCF#/402471354_list-Resource-Form-Cell-Line) under subsection Quality.  I should update the `STR` field to `STR Profile` on the mockups

**Dataset**
>verify that accession can also be the ncbi study_id ie phs000328.v2.p1 or maybe change the name?

Yes, but dbGaP calls it `dbGaP Study Accession` I wanted keep those key words the same so it's easy for users to know which field we are referring to instead of guessing, especially since we are not scraping dbGaP. 

>change accession to accession_id
do we want the interface to also say Accession ID? 

**PDX Model** 
Not sure if this going to be helpful but here's the table I got all the fields from. It also has example values, https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5738926/table/T1/?report=objectonly

**Comment by davidsmejia** [comment]
ok well then we should break up accession to be something like `study_id` and `study_id_type`
where the id is the value and the type would be `dbGaP Study Accession` or `Accession ID` or whatever, each form can supply the appropriate metadata

**Comment by davidsmejia** [comment]
@Philinphiladelphia i updated the import sources for geo and sra to be distinct

**Comment by davidsmejia** [comment]
also found a type that would be great if we could fix with this PR
`number_availible_cell_lines` should be `number_available_cell_lines`

**Comment by cgreene** [comment]
@Philinphiladelphia says this was done a long time ago. Closing.
