### ISSUE TITLE
Logging in on Safari gave a 404 error

### ISSUE THREAD

**Issue by dvenprasad** [AlexsLemonade/resources-portal#626]
### Context

I tried to login using safari. the sandbox gives a 404 error. 

### Problem or idea

I'm not sure if this is an issue with sandbox or a deeper issue. 

### Solution or next step

_You can tag others or simply leave it for further investigation, but you must propose a next step towards solving the issue._

**Comment by davidsmejia** [comment]
I have a high degree of certainty this issue no longer exists. Sounds like the redirect was broken at some point but that would have been changed a few times since this issue was opened. We should move on and open a new issue if someone cannot login with safari.

I was able to create an account with the basic login and create-account, I was able to log out and log back in as well on safari.
