### ISSUE TITLE
Use elasticsearch to implement a search endpoint.

### ISSUE THREAD

**Issue by kurtwheeler** [AlexsLemonade/resources-portal#64]
### Context

Users are going to need to search through our resources. 

### Problem or idea

We'll want to use something robust, elasticsearch has worked for us in the past.

### Solution or next step

Add elasticsearch into the project. Create a separate issue to make it work in the cloud.

**Comment by arielsvn** [comment]
On refinebio we used `django-elasticsearch-dsl-drf`, a basic example of how to use it can be found on [their docs](https://django-elasticsearch-dsl-drf.readthedocs.io/en/latest/basic_usage_examples.html#sample-models). In addition to the `Material` model, we would have to add a document, a serializer, and a custom view to return the results.

It might be helpful to also look into the documentation of [django-elasticsearch-dsl](https://django-elasticsearch-dsl.readthedocs.io/en/latest/quickstart.html) since `django-elasticsearch-dsl-drf` depends on it.
